export type InfoLanguage = 'ES' | 'EN' | 'PT' | 'FR';

interface ContentSection {
  title: string;
  body: string;
}

export const DISCLAIMER_CONTENT: Record<InfoLanguage, ContentSection> = {
  ES: {
    title: "Descargo de Responsabilidad (Disclaimer)",
    body: `
      <p class="mb-2"><strong>Verificación Humana Obligatoria:</strong> Todo el contenido generado por esta herramienta debe ser revisado y verificado rigurosamente por un humano antes de ser enviado. La IA puede cometer errores.</p>
      <p class="mb-2"><strong>Privacidad y NDA:</strong> Está terminantemente prohibido ingresar contenido que viole acuerdos de confidencialidad (NDA), información de identificación personal (PII) o datos sensibles de la empresa.</p>
      <p class="mb-2"><strong>Limitación de Responsabilidad:</strong> La herramienta de IA no tiene la capacidad de verificar si el texto ingresado viola un NDA. Por lo tanto, no se debe atribuir ninguna culpa o responsabilidad legal por violaciones de NDA o filtración de datos a la persona que desarrolló o programó esta herramienta. El usuario asume la responsabilidad total del contenido ingresado y generado.</p>
    `
  },
  EN: {
    title: "Disclaimer",
    body: `
      <p class="mb-2"><strong>Mandatory Human Verification:</strong> All content generated by this tool must be rigorously reviewed and verified by a human before sending. AI can make mistakes.</p>
      <p class="mb-2"><strong>Privacy & NDA:</strong> Inputting content that violates Non-Disclosure Agreements (NDA), Personally Identifiable Information (PII), or sensitive company data is strictly prohibited.</p>
      <p class="mb-2"><strong>Limitation of Liability:</strong> The AI tool cannot verify if input text violates an NDA. Therefore, no blame or legal liability for NDA violations or data leaks shall be attributed to the developer/programmer of this tool. The user assumes full responsibility for all input and generated content.</p>
    `
  },
  PT: {
    title: "Isenção de Responsabilidade (Disclaimer)",
    body: `
      <p class="mb-2"><strong>Verificação Humana Obrigatória:</strong> Todo o conteúdo gerado por esta ferramenta deve ser rigorosamente revisado e verificado por um humano antes de ser enviado. A IA pode cometer erros.</p>
      <p class="mb-2"><strong>Privacidade e NDA:</strong> É estritamente proibido inserir conteúdo que viole Acordos de Não Divulgação (NDA), Informações de Identificação Pessoal (PII) ou dados sensíveis da empresa.</p>
      <p class="mb-2"><strong>Limitação de Responsabilidade:</strong> A ferramenta de IA não tem a capacidade de verificar se o texto inserido viola um NDA. Portanto, nenhuma culpa ou responsabilidade legal por violações de NDA ou vazamento de dados deve ser atribuída à pessoa que desenvolveu ou programou esta ferramenta. O usuário assume total responsabilidade pelo conteúdo inserido e gerado.</p>
    `
  },
  FR: {
    title: "Clause de Non-responsabilité",
    body: `
      <p class="mb-2"><strong>Vérification Humaine Obligatoire :</strong> Tout contenu généré par cet outil doit être rigoureusement examiné et vérifié par un humain avant d'être envoyé. L'IA peut commettre des erreurs.</p>
      <p class="mb-2"><strong>Confidentialité et NDA :</strong> Il est strictement interdit de saisir du contenu violant des accords de non-divulgation (NDA), des informations personnellement identifiables (PII) ou des données sensibles de l'entreprise.</p>
      <p class="mb-2"><strong>Limitation de Responsabilité :</strong> L'outil d'IA ne peut pas vérifier si le texte saisi viole un NDA. Par conséquent, aucune faute ou responsabilité légale pour violation de NDA ou fuite de données ne saurait être attribuée à la personne ayant développé ou programmé cet outil. L'utilisateur assume l'entière responsabilité du contenu saisi et généré.</p>
    `
  }
};

export const GUIDE_CONTENT: Record<InfoLanguage, ContentSection> = {
  ES: {
    title: "Guía de Uso",
    body: `
      <div class="space-y-4">
        <div>
          <h3 class="font-bold text-indigo-600 dark:text-indigo-400">Estructura</h3>
          <ul class="list-disc pl-5 space-y-1 mt-1 text-sm">
            <li><strong>Macro Completo:</strong> Tú le das el macro completo en la entrada y la IA solo le da un tono emocional o cambia la personalidad.</li>
            <li><strong>Primer Mensaje:</strong> Tú le das el macro + el problema que estás resolviendo. La IA agrega el saludo inicial (opening) y el cierre (closing).</li>
            <li><strong>Segundo Mensaje:</strong> Esto se usa cuando la persona hace un <em>pushback</em> y necesitamos darle una respuesta y ya no es el primer mensaje. También genera el cierre automáticamente si no lo pones.</li>
          </ul>
        </div>
        
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <h3 class="font-bold text-indigo-600 dark:text-indigo-400">Configuración</h3>
            <ul class="list-disc pl-5 space-y-1 mt-1 text-sm">
              <li><strong>Longitud:</strong> Define qué tan extenso será el mensaje generado.</li>
              <li><strong>Idioma:</strong> Selecciona el idioma de salida (Output).</li>
              <li><strong>Tono Emocional:</strong> Cambia el estilo (Empatía, Profesional, etc.).</li>
              <li><strong>Nosotros / Yo:</strong> Selector de perspectiva. "Yo" (1ª persona) o "Nosotros" (3ª persona/Corporativo).</li>
            </ul>
          </div>
          <div>
            <h3 class="font-bold text-indigo-600 dark:text-indigo-400">Funciones Especiales</h3>
            <ul class="list-disc pl-5 space-y-1 mt-1 text-sm">
              <li><strong>Cierre Final:</strong> Si está activo (True), envía la macro de resolución final indicando que el ticket se cerrará.</li>
              <li><strong>Corregir:</strong> Después de modificar el texto de salida a mano, toca esto para asegurar ortografía y gramática perfecta.</li>
              <li><strong>Diff:</strong> Después de generar, toca esto para ver exactamente qué cambió respecto a la entrada.</li>
            </ul>
          </div>
        </div>
      </div>
    `
  },
  EN: {
    title: "User Guide",
    body: `
      <div class="space-y-4">
        <div>
          <h3 class="font-bold text-indigo-600 dark:text-indigo-400">Structure</h3>
          <ul class="list-disc pl-5 space-y-1 mt-1 text-sm">
            <li><strong>Full Macro:</strong> You provide the full macro input, and the AI only applies the emotional tone or changes the personality.</li>
            <li><strong>First Message:</strong> You provide the macro + the issue being resolved. The AI adds the opening and closing.</li>
            <li><strong>Second Message:</strong> Used when there is a <em>pushback</em> and we need to provide a response that isn't the first message. It also generates the closing automatically if omitted.</li>
          </ul>
        </div>
        
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <h3 class="font-bold text-indigo-600 dark:text-indigo-400">Settings</h3>
            <ul class="list-disc pl-5 space-y-1 mt-1 text-sm">
              <li><strong>Length:</strong> Defines the length of the generated message.</li>
              <li><strong>Language:</strong> Selects the output language.</li>
              <li><strong>Emotional Tone:</strong> Changes the style (Empathy, Professional, etc.).</li>
              <li><strong>We / Me:</strong> Perspective selector. "Me" (1st person) or "We" (3rd person/Corporate).</li>
            </ul>
          </div>
          <div>
            <h3 class="font-bold text-indigo-600 dark:text-indigo-400">Special Functions</h3>
            <ul class="list-disc pl-5 space-y-1 mt-1 text-sm">
              <li><strong>Final Closing:</strong> If active (True), sends the final resolution macro stating the ticket will be closed.</li>
              <li><strong>Correct:</strong> After manually editing the output, click this to ensure perfect spelling and grammar.</li>
              <li><strong>Diff:</strong> After generation, click this to see exactly what changed from the input.</li>
            </ul>
          </div>
        </div>
      </div>
    `
  },
  PT: {
    title: "Guia do Usuário",
    body: `
      <div class="space-y-4">
        <div>
          <h3 class="font-bold text-indigo-600 dark:text-indigo-400">Estrutura</h3>
          <ul class="list-disc pl-5 space-y-1 mt-1 text-sm">
            <li><strong>Macro Completo:</strong> Você fornece o macro completo na entrada e a IA apenas ajusta o tom emocional ou a personalidade.</li>
            <li><strong>Primeira Mensagem:</strong> Você fornece o macro + o problema. A IA adiciona a abertura (opening) e o fechamento (closing).</li>
            <li><strong>Segunda Mensagem:</strong> Usado quando há um <em>pushback</em> e precisamos dar uma resposta de continuidade. Também gera o fechamento se não for colocado.</li>
          </ul>
        </div>
        
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <h3 class="font-bold text-indigo-600 dark:text-indigo-400">Configurações</h3>
            <ul class="list-disc pl-5 space-y-1 mt-1 text-sm">
              <li><strong>Comprimento:</strong> Define a extensão da mensagem gerada.</li>
              <li><strong>Idioma:</strong> Seleciona o idioma de saída.</li>
              <li><strong>Tom Emocional:</strong> Altera o estilo (Empatia, Profissional, etc.).</li>
              <li><strong>Nós / Eu:</strong> Seletor de perspectiva. "Eu" (1ª pessoa) ou "Nós" (3ª pessoa/Corporativo).</li>
            </ul>
          </div>
          <div>
            <h3 class="font-bold text-indigo-600 dark:text-indigo-400">Funções Especiais</h3>
            <ul class="list-disc pl-5 space-y-1 mt-1 text-sm">
              <li><strong>Fechamento Final:</strong> Se ativo (True), envia o macro de resolução final indicando que o ticket será fechado.</li>
              <li><strong>Corrigir:</strong> Após editar o texto de saída manualmente, clique aqui para garantir ortografia perfeita.</li>
              <li><strong>Diff:</strong> Após gerar, clique aqui para ver exatamente o que mudou em relação à entrada.</li>
            </ul>
          </div>
        </div>
      </div>
    `
  },
  FR: {
    title: "Guide d'Utilisation",
    body: `
      <div class="space-y-4">
        <div>
          <h3 class="font-bold text-indigo-600 dark:text-indigo-400">Structure</h3>
          <ul class="list-disc pl-5 space-y-1 mt-1 text-sm">
            <li><strong>Macro Complet :</strong> Vous donnez la macro complète en entrée et l'IA ajuste seulement le ton émotionnel ou la personnalité.</li>
            <li><strong>Premier Message :</strong> Vous donnez la macro + le problème. L'IA ajoute l'ouverture (opening) et la fermeture (closing).</li>
            <li><strong>Deuxième Message :</strong> Utilisé lorsqu'il y a un <em>pushback</em> et que nous devons répondre. Génère également la fermeture si elle est omise.</li>
          </ul>
        </div>
        
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <h3 class="font-bold text-indigo-600 dark:text-indigo-400">Paramètres</h3>
            <ul class="list-disc pl-5 space-y-1 mt-1 text-sm">
              <li><strong>Longueur :</strong> Définit la longueur du message généré.</li>
              <li><strong>Langue :</strong> Sélectionne la langue de sortie.</li>
              <li><strong>Ton Émotionnel :</strong> Change le style (Empathie, Professionnel, etc.).</li>
              <li><strong>Nous / Je :</strong> Sélecteur de perspective. "Je" (1ère personne) ou "Nous" (3ème personne/Entreprise).</li>
            </ul>
          </div>
          <div>
            <h3 class="font-bold text-indigo-600 dark:text-indigo-400">Fonctions Spéciales</h3>
            <ul class="list-disc pl-5 space-y-1 mt-1 text-sm">
              <li><strong>Fermeture Finale :</strong> Si actif (True), envoie la macro de résolution finale indiquant que le ticket sera fermé.</li>
              <li><strong>Corriger :</strong> Après avoir modifié le texte manuellement, cliquez ici pour assurer une orthographe parfaite.</li>
              <li><strong>Diff :</strong> Après génération, cliquez ici pour voir exactement ce qui a changé par rapport à l'entrée.</li>
            </ul>
          </div>
        </div>
      </div>
    `
  }
};